### ISSUE TITLE
Remove unused field

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-spec#2]
We don't really make use of the following field in the createResponse - https://github.com/gardener/machine-spec/blob/master/cmi.proto#L65. We should probably get rid of this. Creating this issue as a reminder.

**Comment by vlerenc** [comment]
Any decision here? Stale issue, keep or close?

**Comment by prashanth26** [comment]
Yes, you are right. I forgot to close this. This issue has been resolved by - https://github.com/gardener/machine-spec/pull/3.
